# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'grpc_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12grpc_service.proto\"%\n\x11SearchFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"5\n\x12SearchFileResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x10\n\x08location\x18\x02 \x01(\t2C\n\nFileSearch\x12\x35\n\nSearchFile\x12\x12.SearchFileRequest\x1a\x13.SearchFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHFILEREQUEST']._serialized_start=22
  _globals['_SEARCHFILEREQUEST']._serialized_end=59
  _globals['_SEARCHFILERESPONSE']._serialized_start=61
  _globals['_SEARCHFILERESPONSE']._serialized_end=114
  _globals['_FILESEARCH']._serialized_start=116
  _globals['_FILESEARCH']._serialized_end=183
# @@protoc_insertion_point(module_scope)
