# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import p2pfileshare_pb2 as p2pfileshare__pb2


class FileShareServiceStub(object):
    """Servicio que define las operaciones de listado, descarga y carga
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListFiles = channel.unary_unary(
                '/p2pfileshare.FileShareService/ListFiles',
                request_serializer=p2pfileshare__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=p2pfileshare__pb2.ListFilesResponse.FromString,
                )
        self.DownloadFile = channel.unary_unary(
                '/p2pfileshare.FileShareService/DownloadFile',
                request_serializer=p2pfileshare__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=p2pfileshare__pb2.DownloadFileResponse.FromString,
                )
        self.UploadFile = channel.unary_unary(
                '/p2pfileshare.FileShareService/UploadFile',
                request_serializer=p2pfileshare__pb2.UploadFileRequest.SerializeToString,
                response_deserializer=p2pfileshare__pb2.UploadFileResponse.FromString,
                )


class FileShareServiceServicer(object):
    """Servicio que define las operaciones de listado, descarga y carga
    """

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileShareServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=p2pfileshare__pb2.ListFilesRequest.FromString,
                    response_serializer=p2pfileshare__pb2.ListFilesResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=p2pfileshare__pb2.DownloadFileRequest.FromString,
                    response_serializer=p2pfileshare__pb2.DownloadFileResponse.SerializeToString,
            ),
            'UploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=p2pfileshare__pb2.UploadFileRequest.FromString,
                    response_serializer=p2pfileshare__pb2.UploadFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p2pfileshare.FileShareService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileShareService(object):
    """Servicio que define las operaciones de listado, descarga y carga
    """

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/p2pfileshare.FileShareService/ListFiles',
            p2pfileshare__pb2.ListFilesRequest.SerializeToString,
            p2pfileshare__pb2.ListFilesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/p2pfileshare.FileShareService/DownloadFile',
            p2pfileshare__pb2.DownloadFileRequest.SerializeToString,
            p2pfileshare__pb2.DownloadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/p2pfileshare.FileShareService/UploadFile',
            p2pfileshare__pb2.UploadFileRequest.SerializeToString,
            p2pfileshare__pb2.UploadFileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
